dist: trusty
sudo: required
language: go
go:
- 1.8.x
go_import_path: github.com/terraform-providers/terraform-provider-ldap
install:
- sudo apt-get install jq
- pip install --upgrade --user awscli
- wget https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb
- sudo dpkg -i vagrant_1.9.7_x86_64.deb
- rm -f vagrant_1.9.7_x86_64.deb
- vagrant plugin install vagrant-aws
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
script:
- travis_wait 120 scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: fPef6n1UiO361xK1xGeyojGYXw5dNR3oqC4gjQWbbNxuK9dLCXrlAbjk1SV6nMFFr70DobwIXmLINlE3iB4+bdb6d3GXtj9V5oa3jNaJ0EohPXLvepNSFTjafbfLhQRVkWt+RCwoYkOv+lqBrEBfwMLDRoLpsgvMjVDInYPFVnt1KeQiFjcLJnRbbCTruSLX99pQjl/II2YWz1QgU89ucbxB378wRvWcy7NyjYWzpeeHsbrGnG22qAXMOX34xF1Dd39MgZIyrX657GLNHTE9SrEI5A5lq/K8YP8E0dsbP3/EHTIfu5LBdgW23Dwz0dAYAlMwQWCdXcZl+iL0yT/C2yM/tVFbaC4bDIoSeCCuT3cTBE1LUDOToV531ultv0BTUGQWPnKgB/4WXeY0cGiiPVhxRFjx1nw+hwSXUkSxAtQqwLUmSPYt3UYGZaQbz4bAyqY29X7Z21S2x4Y8sZdjfqpMlVBWUum54znkEXhEVD9/wKcnyHNOenVPC3RfwcCzDqfYq36f2bnXAFQudPBEdBrnwJvFFXpT1JkkFAXHr6rIvNLBIoIJON9p6gYywu5VRiZkDFdjwsxu0qTDN+KPkea4r4l6hqMzigJGdckXV2gftRC4mZBkb8mqkIwdVipi6RGmcI8UJ1pmbY8uQETzoqoeIkkqHDwG1Ktr0j7fwcs=
  file:
  - bin/terraform-provider-ldap_windows_amd64.exe
  - bin/terraform-provider-ldap_linux_amd64
  - bin/terraform-provider-ldap_darwin_amd64
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: mevansam/terraform-provider-ldap
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: TrNZH+VZ6ouu1o3q5GKrHvC4JLcexR3h+56yQyCeh/Oh/FWtylOwr/Aj14WlDjE4ZPParT6UzHFZsN3nIV7KnjIFRjC37r1rSlR7MViLC4G+GraJYiONroETCczzxQAzvf0nymRhgFC8Uh6SLSJqPiX7rFn/SmXSyKRPowqcVaxJF6VRn0LKl0sI5Z/7IoueAErRcyo4P1vsa051WcoSdym7p29hA9rxItVkDfP/P5ETC7VerHHv8dadX3m2XvFO6SjWhCn64JAxiW5DxJzAjEmUDxcdesT9JKY73wGOSAY4fpr9r9MjJMbJAP8wKf4Cdv75PdBGU72LZVU1X3ZfGy7hXIysBD5ypBJNRwSIopBq9nfCRPwpTvYrUlDQLFDThtl+ysSzGqZ1O8buEJYSEV79zxjXy86Exfu+2cG1Ipdzp7y5BLDKM2wnpX5dAHheL9QBm8o8o6T0CwheJ5XUTBccMfLsAssNfkTn3LoRrvurGDaHmewp/FhkNH7P7+aHul+HLrWEEd9DYud0PeXhq/6r3yzqGBVAs8P6AxfWVEqTq9GhVb7vg+ScjQzdIV8wbJe76hF6dJrBozKCYu9xfRXAO8q0NQJu/ACpHRyMRWm2LcAt907tYCIDm/h8xfrDWj0ET6e5zP+UOLKdqY8lfHhpV/iJzAnTfC1tzHZCl5w=
  - secure: jSRBVj3vJWOfFIWtawfUQUtSI6lAKJkK4AyDgyqf0nt2924jm7rf9hsBj/eeT4SpjlCP+NqooVcBA4kxox7FEORsLYTjMjnQkDDRjDlObbVnwToxbmBoOyCF0n5Npl/QNLXTVFAeUxUPz7YuUpS5Dr0T2iW14OkFGvT4+CtBuddGG+0583C38cPVhgCfo4OfaSasOf3vo9pzkO1m5eHvJyyUwxW6qYklEzJ/8bHkae7Xkyi+92StIGSV+paIFdU8QJDRlXFNPBixJ8Ak7i+YWLgZ7alTObv5j6CIK/t0WDEszoejJpgHmOLKUM/xJgP9ZFpiKJZYnHGownPa+i2U7WEpJKG7dVx31mtJd/470i0o+pNCicMz+veW+in/UIwqCBbmfQacg5WYTKnYBXTbVRLJFJe32DYWsQiE8NvL7pSV7kVddpTvNT9sWnYiZdnEtskw5SmzeXJlTjyx9RZ7lk1qjeg3CFE9JCmFrQ3oFo241c6bMEici/T052rH9JZbpEomYXU1FiHpb+f4oOjFdwTR6kREhGYGes0aJlu5l0OPUWCw/jk2K13YnMTnnjOIcT3N8qriHB6FGlFO8nvo/eEmeF+XVNYq/sH2Pw830INZmCluP/8xnd/37NFkLDoLU7vBHrs4O++19msblFuthwcmjX/FVB2/6oP1Snd0zEQ=
